version: 2
build:
  os: ubuntu-22.04
  tools:
    sphinx: "8.2.3"  # Specify the version of sphinx you want to use
sphinx:
  configuration: docs/conf.py
python:
  version: 3.11
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs